version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: house-of-job:latest

  web:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
